#!/bin/bash

. $(dirname "$0")/env

if [ ! -f "$brewbuild" ]; then
	git clone https://github.com/mxcl/homebrew "$bb"
fi

$brewbuild -v install autoconf automake libtool pkg-config gettext

if [ ! -f "$brew" ]; then
	git clone https://github.com/mxcl/homebrew "$b"
fi

$brew tap jessevdk/codyn

$brew "$@" install --universal \
	autoconf \
	automake \
	libtool \
	glib \
	python \
	fontconfig \
	freetype \
	libpng

$brew "$@" install --universal --without-x --with-glib cairo

$brew "$@" install --universal \
	jessevdk/codyn/gobject-introspection \
	jessevdk/codyn/py3cairo \
	jessevdk/codyn/pygobject3 \
	jessevdk/codyn/py3gobject3 \
	jessevdk/codyn/json-glib

$d/scripts/get-sources
