#!/bin/bash

. $(dirname "$0")/env

if [ ! -f "$brewbuild" ]; then
	git clone https://github.com/mxcl/homebrew "$bb"
fi

$brewbuild install autoconf automake libtool pkg-config gettext

if [ ! -f "$brew" ]; then
	git clone https://github.com/mxcl/homebrew "$b"
fi

$brew install --universal autoconf automake libtool glib gobject-introspection https://raw.github.com/jessevdk/homebrew-codyn/master/pygobject3.rb
