#!/bin/bash

version=$($(dirname $0)/extract-version) || exit 1

. $(dirname "$0")/env

tmp=$(mktemp -d -t make-cdn-pkg)

cp -a "$d/Codyn.framework" "$tmp/"
sudo chown -R root:admin "$tmp/Codyn.framework"

pkgmaker=/Applications/PackageMaker.app/Contents/MacOS/PackageMaker

if [ ! -d "$pkgmaker" ];
then
	pkgmaker=/Developer/Applications/Utilities/PackageMaker.app/Contents/MacOS/PackageMaker
fi

cp -a "$d/Codyn.pmdoc" "$tmp/"
pkg="Codyn-$version.pkg"

mkdir "$tmp/bin"

# Make symbolic links in bin/
for i in $tmp/Codyn.framework/Resources/bin/* $tmp/Codyn.framework/Resources/mono/bin/*; do
	r=${i#$tmp}
	b=$(basename "$i")

	ln -s "/Library/Frameworks/$r" "$tmp/bin/$b"
done

sudo chown -R root:admin "$tmp/bin"

echo "Making package..."

(cd "$tmp" && $pkgmaker -n "$version" -m -d "$tmp/Codyn.pmdoc" -o "$d/$pkg")
sudo rm -rf "$tmp"

sudo chown $(id -u):$(id -g) "$d/$pkg"
echo "Created package in $pkg..."
